### ISSUE TITLE
Consider adding this to "Projects That Use Beast"

### ISSUE THREAD

**Issue by vinniefalco** [heavyeyelid/virthttp#9]
See: https://github.com/boostorg/beast/wiki/Companies-and-Individuals-Using-Beast

Also, I am working on a JSON library (NOT part of Boost yet):

<https://github.com/vinniefalco/json/>

It is of course designed with networking in mind. I have an in-development open source project that uses it:
https://github.com/vinniefalco/BeastLounge

**Comment by AeroStun** [comment]
Will surely do; thanks for showing interest!
